### ISSUE TITLE
Change color

### ISSUE THREAD

**Issue by 0mkara** [mclmza/arc-theme-Red#2]
Is there any way that I can easily replace the `red` color with something else ?

**Comment by miczza** [comment]
You have to edit the CSS files, in what color do you want to change it?

**Comment by 0mkara** [comment]
in arc-red-darker I want to replace the red color with #468966 because that suits my eye. Can you please tell which css file and what property I should edit ?

**Comment by woohooatb** [comment]
$ sudo gedit /usr/share/themes/Arc-Red/gnome-shell/gnome-shell.css
