### ISSUE TITLE
Docky theme for Arc-Dark-Red

### ISSUE THREAD

**Issue by alireza-amirsamimi** [mclmza/arc-theme-Red#3]
Hello
Thanks for your beautiful themes
I made some themes for docky based on your themes color.

https://github.com/alireza-amirsamimi/Arc-Dark-Docky-themes

docky is a dock program like plank and cairo and ...

You can fork my repository or add my repository link to your README file if you like!

thanks :)

**Comment by miczza** [comment]
Added a link to the readme.
