### ISSUE TITLE
GTK 3.20 support?

### ISSUE THREAD

**Issue by ghost** [mclmza/arc-theme-Red#4]
It seem the latest revision of this theme is still broken on GTK3 apps, such as like this:

![screenshot at 2016-08-14 22-32-41](https://cloud.githubusercontent.com/assets/6704448/17656450/0c33690c-626f-11e6-81b7-57522acbfb82.png)

I'm using Arch Linux with MATE desktop environment.

**Comment by woohooatb** [comment]
You have to compile and install it manually. It's working on Fedora gnome 3.20.2.

**Comment by ghost** [comment]
It worked.

Get Outlook for Android

On Sat, Sep 3, 2016 at 12:13 PM -0700, "woohooatb" notifications@github.com wrote:

You have to compile and install it manually. It's working on Fedora gnome 3.20.2.
