### ISSUE TITLE
No minimize, restore, close buttons visualization on ElementaryOS Loki.

### ISSUE THREAD

**Issue by Peluccio** [mclmza/arc-theme-Red#8]
On Firefox, Netbeans, Android Studio, some editors text, etc.
![screenshot from 2016-09-26 19 36 30](https://cloud.githubusercontent.com/assets/22461175/18856547/3248348c-8421-11e6-89d4-ddbf8bfebf41.png)
![screenshot from 2016-09-26 19 36 43](https://cloud.githubusercontent.com/assets/22461175/18856550/325cbf1a-8421-11e6-9cea-60deba86040d.png)
![screenshot from 2016-09-26 19 37 01](https://cloud.githubusercontent.com/assets/22461175/18856548/3250ba4e-8421-11e6-92da-c7c98df52ff8.png)
![screenshot from 2016-09-26 19 39 46](https://cloud.githubusercontent.com/assets/22461175/18856549/32535cae-8421-11e6-82f9-91afd8631f42.png)

Nice theme.

**Comment by miczza** [comment]
What version of GTK are you using?

**Comment by milanarandjelovic** [comment]
Same problem, just install libgtk-3-dev and restart pc

**Comment by Peluccio** [comment]
Problem was resolved installing libgtk-3
